services:
  backend:
    build:
      context: flask
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./src:/src
    ports:
      - 127.0.0.1:8008:9091
    depends_on:
      -  mongo  

  mongo:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017

